#include<stddef.h>/*IncludethisheaderforNULLdefinition*/
#include"dog.h"
/**
*init_dog-initializesavariableoftypestructdog
*@d:pointertothestructdogtoinitialize
*@name:nametoinitialize
*@age:agetoinitialize
*@owner:ownertoinitialize
*/
voidinit_dog(structdog*d,char*name,floatage,char*owner)
{
if(d!=NULL)/*CheckifthepointerisnotNULL*/
{
d->name=name;
d->age=age;
d->owner=owner;
}
}
